"""Make isbn13 unique

Revision ID: 5e5ce504ab85
Revises: 8d00efd0cd84
Create Date: 2026-06-14 19:43:50.470675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e5ce504ab85'
down_revision: Union[str, Sequence[str], None] = '8d00efd0cd84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_isbn13'), table_name='books')
    op.create_index(op.f('ix_books_isbn13'), 'books', ['isbn13'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_isbn13'), table_name='books')
    op.create_index(op.f('ix_books_isbn13'), 'books', ['isbn13'], unique=False)
    # ### end Alembic commands ###
