"""Update Inference Models for Phase 2

Revision ID: 8d00efd0cd84
Revises: a390c5ae5a6e
Create Date: 2026-06-14 19:43:31.599015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d00efd0cd84'
down_revision: Union[str, Sequence[str], None] = 'a390c5ae5a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_books_isbn13'), 'books', type_='unique')
    op.create_index(op.f('ix_books_isbn13'), 'books', ['isbn13'], unique=False)
    op.add_column('detections', sa.Column('matched_book_id', sa.Integer(), nullable=True))
    op.add_column('detections', sa.Column('score_margin', sa.Numeric(), nullable=True))
    op.add_column('detections', sa.Column('status', sa.String(length=50), nullable=False))
    op.create_foreign_key(None, 'detections', 'books', ['matched_book_id'], ['book_id'])
    op.drop_column('detections', 'decision')
    op.drop_column('detections', 'misplacement_score')
    op.add_column('scan_sessions', sa.Column('expected_shelf_start', sa.Numeric(), nullable=True))
    op.add_column('scan_sessions', sa.Column('expected_shelf_end', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_sessions', 'expected_shelf_end')
    op.drop_column('scan_sessions', 'expected_shelf_start')
    op.add_column('detections', sa.Column('misplacement_score', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('detections', sa.Column('decision', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'detections', type_='foreignkey')
    op.drop_column('detections', 'status')
    op.drop_column('detections', 'score_margin')
    op.drop_column('detections', 'matched_book_id')
    op.drop_index(op.f('ix_books_isbn13'), table_name='books')
    op.create_unique_constraint(op.f('uq_books_isbn13'), 'books', ['isbn13'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
