"""Initial catalog models

Revision ID: a390c5ae5a6e
Revises: 
Create Date: 2026-06-14 19:32:22.227572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a390c5ae5a6e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm;')
    op.create_table('books',
    sa.Column('book_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('isbn13', sa.String(length=20), nullable=True),
    sa.Column('bookname', sa.Text(), nullable=False),
    sa.Column('normalized_bookname', sa.Text(), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('normalized_authors', sa.Text(), nullable=True),
    sa.Column('publisher', sa.Text(), nullable=True),
    sa.Column('publication_year', sa.String(length=10), nullable=True),
    sa.Column('book_image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_index('idx_books_name_trgm', 'books', ['normalized_bookname'], unique=False, postgresql_using='gin', postgresql_ops={'normalized_bookname': 'gin_trgm_ops'})
    op.create_index(op.f('ix_books_isbn13'), 'books', ['isbn13'], unique=False)
    op.create_table('scan_sessions',
    sa.Column('scan_session_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('library_code', sa.String(length=20), nullable=False),
    sa.Column('room_name', sa.String(length=200), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('estimated_shelf_start', sa.Numeric(), nullable=True),
    sa.Column('estimated_shelf_end', sa.Numeric(), nullable=True),
    sa.Column('shelf_confidence', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('scan_session_id')
    )
    op.create_table('holdings',
    sa.Column('holding_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('library_code', sa.String(length=20), nullable=False),
    sa.Column('class_no', sa.String(length=50), nullable=True),
    sa.Column('class_no_clean', sa.String(length=50), nullable=True),
    sa.Column('class_no_num', sa.Numeric(), nullable=True),
    sa.Column('book_code', sa.String(length=100), nullable=True),
    sa.Column('call_number', sa.String(length=200), nullable=True),
    sa.Column('normalized_call_number', sa.String(length=200), nullable=True),
    sa.Column('shelf_loc_code', sa.String(length=50), nullable=True),
    sa.Column('shelf_loc_name', sa.String(length=200), nullable=True),
    sa.Column('separate_shelf_code', sa.String(length=50), nullable=True),
    sa.Column('separate_shelf_name', sa.String(length=200), nullable=True),
    sa.Column('copy_code', sa.String(length=50), nullable=True),
    sa.Column('reg_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ),
    sa.PrimaryKeyConstraint('holding_id')
    )
    op.create_index('idx_holdings_library_call_number', 'holdings', ['library_code', 'normalized_call_number'], unique=False)
    op.create_index('idx_holdings_library_class', 'holdings', ['library_code', 'class_no_num'], unique=False)
    op.create_index(op.f('ix_holdings_library_code'), 'holdings', ['library_code'], unique=False)
    op.create_table('detections',
    sa.Column('detection_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_session_id', sa.Integer(), nullable=True),
    sa.Column('frame_no', sa.Integer(), nullable=True),
    sa.Column('detected_order', sa.Integer(), nullable=True),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ocr_raw_text', sa.Text(), nullable=True),
    sa.Column('ocr_title', sa.Text(), nullable=True),
    sa.Column('ocr_author', sa.Text(), nullable=True),
    sa.Column('ocr_call_number', sa.Text(), nullable=True),
    sa.Column('ocr_confidence', sa.Numeric(), nullable=True),
    sa.Column('matched_holding_id', sa.Integer(), nullable=True),
    sa.Column('match_score', sa.Numeric(), nullable=True),
    sa.Column('decision', sa.String(length=50), nullable=True),
    sa.Column('misplacement_score', sa.Numeric(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['matched_holding_id'], ['holdings.holding_id'], ),
    sa.ForeignKeyConstraint(['scan_session_id'], ['scan_sessions.scan_session_id'], ),
    sa.PrimaryKeyConstraint('detection_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detections')
    op.drop_index(op.f('ix_holdings_library_code'), table_name='holdings')
    op.drop_index('idx_holdings_library_class', table_name='holdings')
    op.drop_index('idx_holdings_library_call_number', table_name='holdings')
    op.drop_table('holdings')
    op.drop_table('scan_sessions')
    op.drop_index(op.f('ix_books_isbn13'), table_name='books')
    op.drop_index('idx_books_name_trgm', table_name='books', postgresql_using='gin', postgresql_ops={'normalized_bookname': 'gin_trgm_ops'})
    op.drop_table('books')
    # ### end Alembic commands ###
