/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ScanIndexRouteImport } from './routes/scan/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthSigninIndexRouteImport } from './routes/auth/signin/index'
import { Route as AppVideoAnalysisIndexRouteImport } from './routes/_app/video-analysis/index'
import { Route as AppShelfOpsIndexRouteImport } from './routes/_app/shelf-ops/index'
import { Route as AppProvidersIndexRouteImport } from './routes/_app/providers/index'
import { Route as AppOrganizationsIndexRouteImport } from './routes/_app/organizations/index'
import { Route as AppEvaluationIndexRouteImport } from './routes/_app/evaluation/index'
import { Route as AppDocumentsIndexRouteImport } from './routes/_app/documents/index'
import { Route as AppBooksIndexRouteImport } from './routes/_app/books/index'
import { Route as AppOrganizationsOrganizationIdIndexRouteImport } from './routes/_app/organizations/$organizationId/index'
import { Route as AppDocumentsCreateIndexRouteImport } from './routes/_app/documents/create/index'
import { Route as AppDocumentsSlugIndexRouteImport } from './routes/_app/documents/$slug/index'
import { Route as AppOrganizationsOrganizationIdEditRouteImport } from './routes/_app/organizations/$organizationId/edit'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanIndexRoute = ScanIndexRouteImport.update({
  id: '/scan/',
  path: '/scan/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthSigninIndexRoute = AuthSigninIndexRouteImport.update({
  id: '/auth/signin/',
  path: '/auth/signin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVideoAnalysisIndexRoute = AppVideoAnalysisIndexRouteImport.update({
  id: '/video-analysis/',
  path: '/video-analysis/',
  getParentRoute: () => AppRoute,
} as any)
const AppShelfOpsIndexRoute = AppShelfOpsIndexRouteImport.update({
  id: '/shelf-ops/',
  path: '/shelf-ops/',
  getParentRoute: () => AppRoute,
} as any)
const AppProvidersIndexRoute = AppProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsIndexRoute = AppOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AppRoute,
} as any)
const AppEvaluationIndexRoute = AppEvaluationIndexRouteImport.update({
  id: '/evaluation/',
  path: '/evaluation/',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsIndexRoute = AppDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => AppRoute,
} as any)
const AppBooksIndexRoute = AppBooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsOrganizationIdIndexRoute =
  AppOrganizationsOrganizationIdIndexRouteImport.update({
    id: '/organizations/$organizationId/',
    path: '/organizations/$organizationId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppDocumentsCreateIndexRoute = AppDocumentsCreateIndexRouteImport.update({
  id: '/documents/create/',
  path: '/documents/create/',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsSlugIndexRoute = AppDocumentsSlugIndexRouteImport.update({
  id: '/documents/$slug/',
  path: '/documents/$slug/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsOrganizationIdEditRoute =
  AppOrganizationsOrganizationIdEditRouteImport.update({
    id: '/organizations/$organizationId/edit',
    path: '/organizations/$organizationId/edit',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/scan/': typeof ScanIndexRoute
  '/books/': typeof AppBooksIndexRoute
  '/documents/': typeof AppDocumentsIndexRoute
  '/evaluation/': typeof AppEvaluationIndexRoute
  '/organizations/': typeof AppOrganizationsIndexRoute
  '/providers/': typeof AppProvidersIndexRoute
  '/shelf-ops/': typeof AppShelfOpsIndexRoute
  '/video-analysis/': typeof AppVideoAnalysisIndexRoute
  '/auth/signin/': typeof AuthSigninIndexRoute
  '/organizations/$organizationId/edit': typeof AppOrganizationsOrganizationIdEditRoute
  '/documents/$slug/': typeof AppDocumentsSlugIndexRoute
  '/documents/create/': typeof AppDocumentsCreateIndexRoute
  '/organizations/$organizationId/': typeof AppOrganizationsOrganizationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/scan': typeof ScanIndexRoute
  '/books': typeof AppBooksIndexRoute
  '/documents': typeof AppDocumentsIndexRoute
  '/evaluation': typeof AppEvaluationIndexRoute
  '/organizations': typeof AppOrganizationsIndexRoute
  '/providers': typeof AppProvidersIndexRoute
  '/shelf-ops': typeof AppShelfOpsIndexRoute
  '/video-analysis': typeof AppVideoAnalysisIndexRoute
  '/auth/signin': typeof AuthSigninIndexRoute
  '/organizations/$organizationId/edit': typeof AppOrganizationsOrganizationIdEditRoute
  '/documents/$slug': typeof AppDocumentsSlugIndexRoute
  '/documents/create': typeof AppDocumentsCreateIndexRoute
  '/organizations/$organizationId': typeof AppOrganizationsOrganizationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/scan/': typeof ScanIndexRoute
  '/_app/books/': typeof AppBooksIndexRoute
  '/_app/documents/': typeof AppDocumentsIndexRoute
  '/_app/evaluation/': typeof AppEvaluationIndexRoute
  '/_app/organizations/': typeof AppOrganizationsIndexRoute
  '/_app/providers/': typeof AppProvidersIndexRoute
  '/_app/shelf-ops/': typeof AppShelfOpsIndexRoute
  '/_app/video-analysis/': typeof AppVideoAnalysisIndexRoute
  '/auth/signin/': typeof AuthSigninIndexRoute
  '/_app/organizations/$organizationId/edit': typeof AppOrganizationsOrganizationIdEditRoute
  '/_app/documents/$slug/': typeof AppDocumentsSlugIndexRoute
  '/_app/documents/create/': typeof AppDocumentsCreateIndexRoute
  '/_app/organizations/$organizationId/': typeof AppOrganizationsOrganizationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/scan/'
    | '/books/'
    | '/documents/'
    | '/evaluation/'
    | '/organizations/'
    | '/providers/'
    | '/shelf-ops/'
    | '/video-analysis/'
    | '/auth/signin/'
    | '/organizations/$organizationId/edit'
    | '/documents/$slug/'
    | '/documents/create/'
    | '/organizations/$organizationId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/scan'
    | '/books'
    | '/documents'
    | '/evaluation'
    | '/organizations'
    | '/providers'
    | '/shelf-ops'
    | '/video-analysis'
    | '/auth/signin'
    | '/organizations/$organizationId/edit'
    | '/documents/$slug'
    | '/documents/create'
    | '/organizations/$organizationId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/scan/'
    | '/_app/books/'
    | '/_app/documents/'
    | '/_app/evaluation/'
    | '/_app/organizations/'
    | '/_app/providers/'
    | '/_app/shelf-ops/'
    | '/_app/video-analysis/'
    | '/auth/signin/'
    | '/_app/organizations/$organizationId/edit'
    | '/_app/documents/$slug/'
    | '/_app/documents/create/'
    | '/_app/organizations/$organizationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ScanIndexRoute: typeof ScanIndexRoute
  AuthSigninIndexRoute: typeof AuthSigninIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/': {
      id: '/scan/'
      path: '/scan'
      fullPath: '/scan/'
      preLoaderRoute: typeof ScanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/signin/': {
      id: '/auth/signin/'
      path: '/auth/signin'
      fullPath: '/auth/signin/'
      preLoaderRoute: typeof AuthSigninIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/video-analysis/': {
      id: '/_app/video-analysis/'
      path: '/video-analysis'
      fullPath: '/video-analysis/'
      preLoaderRoute: typeof AppVideoAnalysisIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shelf-ops/': {
      id: '/_app/shelf-ops/'
      path: '/shelf-ops'
      fullPath: '/shelf-ops/'
      preLoaderRoute: typeof AppShelfOpsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/providers/': {
      id: '/_app/providers/'
      path: '/providers'
      fullPath: '/providers/'
      preLoaderRoute: typeof AppProvidersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations/': {
      id: '/_app/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof AppOrganizationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/evaluation/': {
      id: '/_app/evaluation/'
      path: '/evaluation'
      fullPath: '/evaluation/'
      preLoaderRoute: typeof AppEvaluationIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents/': {
      id: '/_app/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof AppDocumentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/books/': {
      id: '/_app/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof AppBooksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations/$organizationId/': {
      id: '/_app/organizations/$organizationId/'
      path: '/organizations/$organizationId'
      fullPath: '/organizations/$organizationId/'
      preLoaderRoute: typeof AppOrganizationsOrganizationIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents/create/': {
      id: '/_app/documents/create/'
      path: '/documents/create'
      fullPath: '/documents/create/'
      preLoaderRoute: typeof AppDocumentsCreateIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents/$slug/': {
      id: '/_app/documents/$slug/'
      path: '/documents/$slug'
      fullPath: '/documents/$slug/'
      preLoaderRoute: typeof AppDocumentsSlugIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations/$organizationId/edit': {
      id: '/_app/organizations/$organizationId/edit'
      path: '/organizations/$organizationId/edit'
      fullPath: '/organizations/$organizationId/edit'
      preLoaderRoute: typeof AppOrganizationsOrganizationIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppBooksIndexRoute: typeof AppBooksIndexRoute
  AppDocumentsIndexRoute: typeof AppDocumentsIndexRoute
  AppEvaluationIndexRoute: typeof AppEvaluationIndexRoute
  AppOrganizationsIndexRoute: typeof AppOrganizationsIndexRoute
  AppProvidersIndexRoute: typeof AppProvidersIndexRoute
  AppShelfOpsIndexRoute: typeof AppShelfOpsIndexRoute
  AppVideoAnalysisIndexRoute: typeof AppVideoAnalysisIndexRoute
  AppOrganizationsOrganizationIdEditRoute: typeof AppOrganizationsOrganizationIdEditRoute
  AppDocumentsSlugIndexRoute: typeof AppDocumentsSlugIndexRoute
  AppDocumentsCreateIndexRoute: typeof AppDocumentsCreateIndexRoute
  AppOrganizationsOrganizationIdIndexRoute: typeof AppOrganizationsOrganizationIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppBooksIndexRoute: AppBooksIndexRoute,
  AppDocumentsIndexRoute: AppDocumentsIndexRoute,
  AppEvaluationIndexRoute: AppEvaluationIndexRoute,
  AppOrganizationsIndexRoute: AppOrganizationsIndexRoute,
  AppProvidersIndexRoute: AppProvidersIndexRoute,
  AppShelfOpsIndexRoute: AppShelfOpsIndexRoute,
  AppVideoAnalysisIndexRoute: AppVideoAnalysisIndexRoute,
  AppOrganizationsOrganizationIdEditRoute:
    AppOrganizationsOrganizationIdEditRoute,
  AppDocumentsSlugIndexRoute: AppDocumentsSlugIndexRoute,
  AppDocumentsCreateIndexRoute: AppDocumentsCreateIndexRoute,
  AppOrganizationsOrganizationIdIndexRoute:
    AppOrganizationsOrganizationIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ScanIndexRoute: ScanIndexRoute,
  AuthSigninIndexRoute: AuthSigninIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
